name: Proxy Checker (Deep Scan for RU)

on:
  schedule:
    - cron: '0 */6 * * *' 
  workflow_dispatch: 

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Download LiteSpeedTest (Fixed Link)
        run: |
          wget https://github.com/xxf098/LiteSpeedTest/releases/download/v0.15.0/lite-linux-amd64-v0.15.0.gz
          gunzip lite-linux-amd64-v0.15.0.gz
          mv lite-linux-amd64-v0.15.0 lite
          chmod +x lite

      - name: Run Script (Parse & Dual Check)
        run: python main.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add proxies/
          git commit -m "Auto-update: Proxies checked via CF & Yandex" || echo "No changes"
          git push
